/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.18
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ReadApiAccessPolicyRequest,
    ReadApiAccessPolicyRequestFromJSON,
    ReadApiAccessPolicyRequestToJSON,
    ReadApiAccessPolicyResponse,
    ReadApiAccessPolicyResponseFromJSON,
    ReadApiAccessPolicyResponseToJSON,
    UpdateApiAccessPolicyRequest,
    UpdateApiAccessPolicyRequestFromJSON,
    UpdateApiAccessPolicyRequestToJSON,
    UpdateApiAccessPolicyResponse,
    UpdateApiAccessPolicyResponseFromJSON,
    UpdateApiAccessPolicyResponseToJSON,
} from '../models';

export interface ReadApiAccessPolicyOperationRequest {
    readApiAccessPolicyRequest?: ReadApiAccessPolicyRequest;
}

export interface UpdateApiAccessPolicyOperationRequest {
    updateApiAccessPolicyRequest?: UpdateApiAccessPolicyRequest;
}

/**
 * ApiAccessPolicyApi - interface
 * 
 * @export
 * @interface ApiAccessPolicyApiInterface
 */
export interface ApiAccessPolicyApiInterface {
    /**
     * 
     * @param {ReadApiAccessPolicyRequest} [readApiAccessPolicyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiAccessPolicyApiInterface
     */
    readApiAccessPolicyRaw(requestParameters: ReadApiAccessPolicyOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadApiAccessPolicyResponse>>;

    /**
     */
    readApiAccessPolicy(requestParameters: ReadApiAccessPolicyOperationRequest, initOverrides?: RequestInit): Promise<ReadApiAccessPolicyResponse>;

    /**
     * 
     * @param {UpdateApiAccessPolicyRequest} [updateApiAccessPolicyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiAccessPolicyApiInterface
     */
    updateApiAccessPolicyRaw(requestParameters: UpdateApiAccessPolicyOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UpdateApiAccessPolicyResponse>>;

    /**
     */
    updateApiAccessPolicy(requestParameters: UpdateApiAccessPolicyOperationRequest, initOverrides?: RequestInit): Promise<UpdateApiAccessPolicyResponse>;

}

/**
 * 
 */
export class ApiAccessPolicyApi extends runtime.BaseAPI implements ApiAccessPolicyApiInterface {

    /**
     */
    async readApiAccessPolicyRaw(requestParameters: ReadApiAccessPolicyOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadApiAccessPolicyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuthSec authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ReadApiAccessPolicy`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadApiAccessPolicyRequestToJSON(requestParameters.readApiAccessPolicyRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadApiAccessPolicyResponseFromJSON(jsonValue));
    }

    /**
     */
    async readApiAccessPolicy(requestParameters: ReadApiAccessPolicyOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadApiAccessPolicyResponse> {
        const response = await this.readApiAccessPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateApiAccessPolicyRaw(requestParameters: UpdateApiAccessPolicyOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UpdateApiAccessPolicyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuthSec authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/UpdateApiAccessPolicy`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateApiAccessPolicyRequestToJSON(requestParameters.updateApiAccessPolicyRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateApiAccessPolicyResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateApiAccessPolicy(requestParameters: UpdateApiAccessPolicyOperationRequest = {}, initOverrides?: RequestInit): Promise<UpdateApiAccessPolicyResponse> {
        const response = await this.updateApiAccessPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
