/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.18
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateDhcpOptionsRequest,
    CreateDhcpOptionsRequestFromJSON,
    CreateDhcpOptionsRequestToJSON,
    CreateDhcpOptionsResponse,
    CreateDhcpOptionsResponseFromJSON,
    CreateDhcpOptionsResponseToJSON,
    DeleteDhcpOptionsRequest,
    DeleteDhcpOptionsRequestFromJSON,
    DeleteDhcpOptionsRequestToJSON,
    DeleteDhcpOptionsResponse,
    DeleteDhcpOptionsResponseFromJSON,
    DeleteDhcpOptionsResponseToJSON,
    ReadDhcpOptionsRequest,
    ReadDhcpOptionsRequestFromJSON,
    ReadDhcpOptionsRequestToJSON,
    ReadDhcpOptionsResponse,
    ReadDhcpOptionsResponseFromJSON,
    ReadDhcpOptionsResponseToJSON,
} from '../models';

export interface CreateDhcpOptionsOperationRequest {
    createDhcpOptionsRequest?: CreateDhcpOptionsRequest;
}

export interface DeleteDhcpOptionsOperationRequest {
    deleteDhcpOptionsRequest?: DeleteDhcpOptionsRequest;
}

export interface ReadDhcpOptionsOperationRequest {
    readDhcpOptionsRequest?: ReadDhcpOptionsRequest;
}

/**
 * DhcpOptionApi - interface
 * 
 * @export
 * @interface DhcpOptionApiInterface
 */
export interface DhcpOptionApiInterface {
    /**
     * 
     * @param {CreateDhcpOptionsRequest} [createDhcpOptionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DhcpOptionApiInterface
     */
    createDhcpOptionsRaw(requestParameters: CreateDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateDhcpOptionsResponse>>;

    /**
     */
    createDhcpOptions(requestParameters: CreateDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<CreateDhcpOptionsResponse>;

    /**
     * 
     * @param {DeleteDhcpOptionsRequest} [deleteDhcpOptionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DhcpOptionApiInterface
     */
    deleteDhcpOptionsRaw(requestParameters: DeleteDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteDhcpOptionsResponse>>;

    /**
     */
    deleteDhcpOptions(requestParameters: DeleteDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<DeleteDhcpOptionsResponse>;

    /**
     * 
     * @param {ReadDhcpOptionsRequest} [readDhcpOptionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DhcpOptionApiInterface
     */
    readDhcpOptionsRaw(requestParameters: ReadDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadDhcpOptionsResponse>>;

    /**
     */
    readDhcpOptions(requestParameters: ReadDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<ReadDhcpOptionsResponse>;

}

/**
 * 
 */
export class DhcpOptionApi extends runtime.BaseAPI implements DhcpOptionApiInterface {

    /**
     */
    async createDhcpOptionsRaw(requestParameters: CreateDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateDhcpOptionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/CreateDhcpOptions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDhcpOptionsRequestToJSON(requestParameters.createDhcpOptionsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDhcpOptionsResponseFromJSON(jsonValue));
    }

    /**
     */
    async createDhcpOptions(requestParameters: CreateDhcpOptionsOperationRequest = {}, initOverrides?: RequestInit): Promise<CreateDhcpOptionsResponse> {
        const response = await this.createDhcpOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteDhcpOptionsRaw(requestParameters: DeleteDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteDhcpOptionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/DeleteDhcpOptions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteDhcpOptionsRequestToJSON(requestParameters.deleteDhcpOptionsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteDhcpOptionsResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteDhcpOptions(requestParameters: DeleteDhcpOptionsOperationRequest = {}, initOverrides?: RequestInit): Promise<DeleteDhcpOptionsResponse> {
        const response = await this.deleteDhcpOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readDhcpOptionsRaw(requestParameters: ReadDhcpOptionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadDhcpOptionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ReadDhcpOptions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadDhcpOptionsRequestToJSON(requestParameters.readDhcpOptionsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadDhcpOptionsResponseFromJSON(jsonValue));
    }

    /**
     */
    async readDhcpOptions(requestParameters: ReadDhcpOptionsOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadDhcpOptionsResponse> {
        const response = await this.readDhcpOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
