/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.18
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateDirectLinkRequest,
    CreateDirectLinkRequestFromJSON,
    CreateDirectLinkRequestToJSON,
    CreateDirectLinkResponse,
    CreateDirectLinkResponseFromJSON,
    CreateDirectLinkResponseToJSON,
    DeleteDirectLinkRequest,
    DeleteDirectLinkRequestFromJSON,
    DeleteDirectLinkRequestToJSON,
    DeleteDirectLinkResponse,
    DeleteDirectLinkResponseFromJSON,
    DeleteDirectLinkResponseToJSON,
    ReadDirectLinksRequest,
    ReadDirectLinksRequestFromJSON,
    ReadDirectLinksRequestToJSON,
    ReadDirectLinksResponse,
    ReadDirectLinksResponseFromJSON,
    ReadDirectLinksResponseToJSON,
} from '../models';

export interface CreateDirectLinkOperationRequest {
    createDirectLinkRequest?: CreateDirectLinkRequest;
}

export interface DeleteDirectLinkOperationRequest {
    deleteDirectLinkRequest?: DeleteDirectLinkRequest;
}

export interface ReadDirectLinksOperationRequest {
    readDirectLinksRequest?: ReadDirectLinksRequest;
}

/**
 * DirectLinkApi - interface
 * 
 * @export
 * @interface DirectLinkApiInterface
 */
export interface DirectLinkApiInterface {
    /**
     * 
     * @param {CreateDirectLinkRequest} [createDirectLinkRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DirectLinkApiInterface
     */
    createDirectLinkRaw(requestParameters: CreateDirectLinkOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateDirectLinkResponse>>;

    /**
     */
    createDirectLink(requestParameters: CreateDirectLinkOperationRequest, initOverrides?: RequestInit): Promise<CreateDirectLinkResponse>;

    /**
     * 
     * @param {DeleteDirectLinkRequest} [deleteDirectLinkRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DirectLinkApiInterface
     */
    deleteDirectLinkRaw(requestParameters: DeleteDirectLinkOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteDirectLinkResponse>>;

    /**
     */
    deleteDirectLink(requestParameters: DeleteDirectLinkOperationRequest, initOverrides?: RequestInit): Promise<DeleteDirectLinkResponse>;

    /**
     * 
     * @param {ReadDirectLinksRequest} [readDirectLinksRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DirectLinkApiInterface
     */
    readDirectLinksRaw(requestParameters: ReadDirectLinksOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadDirectLinksResponse>>;

    /**
     */
    readDirectLinks(requestParameters: ReadDirectLinksOperationRequest, initOverrides?: RequestInit): Promise<ReadDirectLinksResponse>;

}

/**
 * 
 */
export class DirectLinkApi extends runtime.BaseAPI implements DirectLinkApiInterface {

    /**
     */
    async createDirectLinkRaw(requestParameters: CreateDirectLinkOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateDirectLinkResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/CreateDirectLink`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDirectLinkRequestToJSON(requestParameters.createDirectLinkRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDirectLinkResponseFromJSON(jsonValue));
    }

    /**
     */
    async createDirectLink(requestParameters: CreateDirectLinkOperationRequest = {}, initOverrides?: RequestInit): Promise<CreateDirectLinkResponse> {
        const response = await this.createDirectLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteDirectLinkRaw(requestParameters: DeleteDirectLinkOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteDirectLinkResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/DeleteDirectLink`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteDirectLinkRequestToJSON(requestParameters.deleteDirectLinkRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteDirectLinkResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteDirectLink(requestParameters: DeleteDirectLinkOperationRequest = {}, initOverrides?: RequestInit): Promise<DeleteDirectLinkResponse> {
        const response = await this.deleteDirectLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readDirectLinksRaw(requestParameters: ReadDirectLinksOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadDirectLinksResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ReadDirectLinks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadDirectLinksRequestToJSON(requestParameters.readDirectLinksRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadDirectLinksResponseFromJSON(jsonValue));
    }

    /**
     */
    async readDirectLinks(requestParameters: ReadDirectLinksOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadDirectLinksResponse> {
        const response = await this.readDirectLinksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
