/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.18
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import * as runtime from '../runtime.js';
import { CreateVirtualGatewayRequestToJSON, CreateVirtualGatewayResponseFromJSON, DeleteVirtualGatewayRequestToJSON, DeleteVirtualGatewayResponseFromJSON, LinkVirtualGatewayRequestToJSON, LinkVirtualGatewayResponseFromJSON, ReadVirtualGatewaysRequestToJSON, ReadVirtualGatewaysResponseFromJSON, UnlinkVirtualGatewayRequestToJSON, UnlinkVirtualGatewayResponseFromJSON, UpdateRoutePropagationRequestToJSON, UpdateRoutePropagationResponseFromJSON, } from '../models/index.js';
/**
 *
 */
export class VirtualGatewayApi extends runtime.BaseAPI {
    /**
     */
    createVirtualGatewayRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/CreateVirtualGateway`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: CreateVirtualGatewayRequestToJSON(requestParameters.createVirtualGatewayRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => CreateVirtualGatewayResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    createVirtualGateway(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.createVirtualGatewayRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    deleteVirtualGatewayRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/DeleteVirtualGateway`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: DeleteVirtualGatewayRequestToJSON(requestParameters.deleteVirtualGatewayRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => DeleteVirtualGatewayResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    deleteVirtualGateway(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.deleteVirtualGatewayRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    linkVirtualGatewayRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/LinkVirtualGateway`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: LinkVirtualGatewayRequestToJSON(requestParameters.linkVirtualGatewayRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => LinkVirtualGatewayResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    linkVirtualGateway(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.linkVirtualGatewayRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    readVirtualGatewaysRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/ReadVirtualGateways`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: ReadVirtualGatewaysRequestToJSON(requestParameters.readVirtualGatewaysRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => ReadVirtualGatewaysResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    readVirtualGateways(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.readVirtualGatewaysRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    unlinkVirtualGatewayRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/UnlinkVirtualGateway`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: UnlinkVirtualGatewayRequestToJSON(requestParameters.unlinkVirtualGatewayRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => UnlinkVirtualGatewayResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    unlinkVirtualGateway(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.unlinkVirtualGatewayRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    updateRoutePropagationRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/UpdateRoutePropagation`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: UpdateRoutePropagationRequestToJSON(requestParameters.updateRoutePropagationRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => UpdateRoutePropagationResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    updateRoutePropagation(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.updateRoutePropagationRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
}
