/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.18
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateVmsRequest,
    CreateVmsRequestFromJSON,
    CreateVmsRequestToJSON,
    CreateVmsResponse,
    CreateVmsResponseFromJSON,
    CreateVmsResponseToJSON,
    DeleteVmsRequest,
    DeleteVmsRequestFromJSON,
    DeleteVmsRequestToJSON,
    DeleteVmsResponse,
    DeleteVmsResponseFromJSON,
    DeleteVmsResponseToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ReadAdminPasswordRequest,
    ReadAdminPasswordRequestFromJSON,
    ReadAdminPasswordRequestToJSON,
    ReadAdminPasswordResponse,
    ReadAdminPasswordResponseFromJSON,
    ReadAdminPasswordResponseToJSON,
    ReadConsoleOutputRequest,
    ReadConsoleOutputRequestFromJSON,
    ReadConsoleOutputRequestToJSON,
    ReadConsoleOutputResponse,
    ReadConsoleOutputResponseFromJSON,
    ReadConsoleOutputResponseToJSON,
    ReadVmTypesRequest,
    ReadVmTypesRequestFromJSON,
    ReadVmTypesRequestToJSON,
    ReadVmTypesResponse,
    ReadVmTypesResponseFromJSON,
    ReadVmTypesResponseToJSON,
    ReadVmsRequest,
    ReadVmsRequestFromJSON,
    ReadVmsRequestToJSON,
    ReadVmsResponse,
    ReadVmsResponseFromJSON,
    ReadVmsResponseToJSON,
    ReadVmsStateRequest,
    ReadVmsStateRequestFromJSON,
    ReadVmsStateRequestToJSON,
    ReadVmsStateResponse,
    ReadVmsStateResponseFromJSON,
    ReadVmsStateResponseToJSON,
    RebootVmsRequest,
    RebootVmsRequestFromJSON,
    RebootVmsRequestToJSON,
    RebootVmsResponse,
    RebootVmsResponseFromJSON,
    RebootVmsResponseToJSON,
    StartVmsRequest,
    StartVmsRequestFromJSON,
    StartVmsRequestToJSON,
    StartVmsResponse,
    StartVmsResponseFromJSON,
    StartVmsResponseToJSON,
    StopVmsRequest,
    StopVmsRequestFromJSON,
    StopVmsRequestToJSON,
    StopVmsResponse,
    StopVmsResponseFromJSON,
    StopVmsResponseToJSON,
    UpdateVmRequest,
    UpdateVmRequestFromJSON,
    UpdateVmRequestToJSON,
    UpdateVmResponse,
    UpdateVmResponseFromJSON,
    UpdateVmResponseToJSON,
} from '../models';

export interface CreateVmsOperationRequest {
    createVmsRequest?: CreateVmsRequest;
}

export interface DeleteVmsOperationRequest {
    deleteVmsRequest?: DeleteVmsRequest;
}

export interface ReadAdminPasswordOperationRequest {
    readAdminPasswordRequest?: ReadAdminPasswordRequest;
}

export interface ReadConsoleOutputOperationRequest {
    readConsoleOutputRequest?: ReadConsoleOutputRequest;
}

export interface ReadVmTypesOperationRequest {
    readVmTypesRequest?: ReadVmTypesRequest;
}

export interface ReadVmsOperationRequest {
    readVmsRequest?: ReadVmsRequest;
}

export interface ReadVmsStateOperationRequest {
    readVmsStateRequest?: ReadVmsStateRequest;
}

export interface RebootVmsOperationRequest {
    rebootVmsRequest?: RebootVmsRequest;
}

export interface StartVmsOperationRequest {
    startVmsRequest?: StartVmsRequest;
}

export interface StopVmsOperationRequest {
    stopVmsRequest?: StopVmsRequest;
}

export interface UpdateVmOperationRequest {
    updateVmRequest?: UpdateVmRequest;
}

/**
 * VmApi - interface
 * 
 * @export
 * @interface VmApiInterface
 */
export interface VmApiInterface {
    /**
     * 
     * @param {CreateVmsRequest} [createVmsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    createVmsRaw(requestParameters: CreateVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateVmsResponse>>;

    /**
     */
    createVms(requestParameters: CreateVmsOperationRequest, initOverrides?: RequestInit): Promise<CreateVmsResponse>;

    /**
     * 
     * @param {DeleteVmsRequest} [deleteVmsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    deleteVmsRaw(requestParameters: DeleteVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteVmsResponse>>;

    /**
     */
    deleteVms(requestParameters: DeleteVmsOperationRequest, initOverrides?: RequestInit): Promise<DeleteVmsResponse>;

    /**
     * 
     * @param {ReadAdminPasswordRequest} [readAdminPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    readAdminPasswordRaw(requestParameters: ReadAdminPasswordOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadAdminPasswordResponse>>;

    /**
     */
    readAdminPassword(requestParameters: ReadAdminPasswordOperationRequest, initOverrides?: RequestInit): Promise<ReadAdminPasswordResponse>;

    /**
     * 
     * @param {ReadConsoleOutputRequest} [readConsoleOutputRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    readConsoleOutputRaw(requestParameters: ReadConsoleOutputOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadConsoleOutputResponse>>;

    /**
     */
    readConsoleOutput(requestParameters: ReadConsoleOutputOperationRequest, initOverrides?: RequestInit): Promise<ReadConsoleOutputResponse>;

    /**
     * 
     * @param {ReadVmTypesRequest} [readVmTypesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    readVmTypesRaw(requestParameters: ReadVmTypesOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadVmTypesResponse>>;

    /**
     */
    readVmTypes(requestParameters: ReadVmTypesOperationRequest, initOverrides?: RequestInit): Promise<ReadVmTypesResponse>;

    /**
     * 
     * @param {ReadVmsRequest} [readVmsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    readVmsRaw(requestParameters: ReadVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadVmsResponse>>;

    /**
     */
    readVms(requestParameters: ReadVmsOperationRequest, initOverrides?: RequestInit): Promise<ReadVmsResponse>;

    /**
     * 
     * @param {ReadVmsStateRequest} [readVmsStateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    readVmsStateRaw(requestParameters: ReadVmsStateOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadVmsStateResponse>>;

    /**
     */
    readVmsState(requestParameters: ReadVmsStateOperationRequest, initOverrides?: RequestInit): Promise<ReadVmsStateResponse>;

    /**
     * 
     * @param {RebootVmsRequest} [rebootVmsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    rebootVmsRaw(requestParameters: RebootVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<RebootVmsResponse>>;

    /**
     */
    rebootVms(requestParameters: RebootVmsOperationRequest, initOverrides?: RequestInit): Promise<RebootVmsResponse>;

    /**
     * 
     * @param {StartVmsRequest} [startVmsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    startVmsRaw(requestParameters: StartVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<StartVmsResponse>>;

    /**
     */
    startVms(requestParameters: StartVmsOperationRequest, initOverrides?: RequestInit): Promise<StartVmsResponse>;

    /**
     * 
     * @param {StopVmsRequest} [stopVmsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    stopVmsRaw(requestParameters: StopVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<StopVmsResponse>>;

    /**
     */
    stopVms(requestParameters: StopVmsOperationRequest, initOverrides?: RequestInit): Promise<StopVmsResponse>;

    /**
     * 
     * @param {UpdateVmRequest} [updateVmRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VmApiInterface
     */
    updateVmRaw(requestParameters: UpdateVmOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UpdateVmResponse>>;

    /**
     */
    updateVm(requestParameters: UpdateVmOperationRequest, initOverrides?: RequestInit): Promise<UpdateVmResponse>;

}

/**
 * 
 */
export class VmApi extends runtime.BaseAPI implements VmApiInterface {

    /**
     */
    async createVmsRaw(requestParameters: CreateVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateVmsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/CreateVms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVmsRequestToJSON(requestParameters.createVmsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateVmsResponseFromJSON(jsonValue));
    }

    /**
     */
    async createVms(requestParameters: CreateVmsOperationRequest = {}, initOverrides?: RequestInit): Promise<CreateVmsResponse> {
        const response = await this.createVmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteVmsRaw(requestParameters: DeleteVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteVmsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/DeleteVms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteVmsRequestToJSON(requestParameters.deleteVmsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteVmsResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteVms(requestParameters: DeleteVmsOperationRequest = {}, initOverrides?: RequestInit): Promise<DeleteVmsResponse> {
        const response = await this.deleteVmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readAdminPasswordRaw(requestParameters: ReadAdminPasswordOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadAdminPasswordResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ReadAdminPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadAdminPasswordRequestToJSON(requestParameters.readAdminPasswordRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadAdminPasswordResponseFromJSON(jsonValue));
    }

    /**
     */
    async readAdminPassword(requestParameters: ReadAdminPasswordOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadAdminPasswordResponse> {
        const response = await this.readAdminPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readConsoleOutputRaw(requestParameters: ReadConsoleOutputOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadConsoleOutputResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ReadConsoleOutput`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadConsoleOutputRequestToJSON(requestParameters.readConsoleOutputRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadConsoleOutputResponseFromJSON(jsonValue));
    }

    /**
     */
    async readConsoleOutput(requestParameters: ReadConsoleOutputOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadConsoleOutputResponse> {
        const response = await this.readConsoleOutputRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readVmTypesRaw(requestParameters: ReadVmTypesOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadVmTypesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ReadVmTypes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadVmTypesRequestToJSON(requestParameters.readVmTypesRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadVmTypesResponseFromJSON(jsonValue));
    }

    /**
     */
    async readVmTypes(requestParameters: ReadVmTypesOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadVmTypesResponse> {
        const response = await this.readVmTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readVmsRaw(requestParameters: ReadVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadVmsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ReadVms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadVmsRequestToJSON(requestParameters.readVmsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadVmsResponseFromJSON(jsonValue));
    }

    /**
     */
    async readVms(requestParameters: ReadVmsOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadVmsResponse> {
        const response = await this.readVmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readVmsStateRaw(requestParameters: ReadVmsStateOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReadVmsStateResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ReadVmsState`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReadVmsStateRequestToJSON(requestParameters.readVmsStateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadVmsStateResponseFromJSON(jsonValue));
    }

    /**
     */
    async readVmsState(requestParameters: ReadVmsStateOperationRequest = {}, initOverrides?: RequestInit): Promise<ReadVmsStateResponse> {
        const response = await this.readVmsStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async rebootVmsRaw(requestParameters: RebootVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<RebootVmsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/RebootVms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RebootVmsRequestToJSON(requestParameters.rebootVmsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RebootVmsResponseFromJSON(jsonValue));
    }

    /**
     */
    async rebootVms(requestParameters: RebootVmsOperationRequest = {}, initOverrides?: RequestInit): Promise<RebootVmsResponse> {
        const response = await this.rebootVmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async startVmsRaw(requestParameters: StartVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<StartVmsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/StartVms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartVmsRequestToJSON(requestParameters.startVmsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartVmsResponseFromJSON(jsonValue));
    }

    /**
     */
    async startVms(requestParameters: StartVmsOperationRequest = {}, initOverrides?: RequestInit): Promise<StartVmsResponse> {
        const response = await this.startVmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async stopVmsRaw(requestParameters: StopVmsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<StopVmsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/StopVms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StopVmsRequestToJSON(requestParameters.stopVmsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopVmsResponseFromJSON(jsonValue));
    }

    /**
     */
    async stopVms(requestParameters: StopVmsOperationRequest = {}, initOverrides?: RequestInit): Promise<StopVmsResponse> {
        const response = await this.stopVmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateVmRaw(requestParameters: UpdateVmOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UpdateVmResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/UpdateVm`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateVmRequestToJSON(requestParameters.updateVmRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateVmResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateVm(requestParameters: UpdateVmOperationRequest = {}, initOverrides?: RequestInit): Promise<UpdateVmResponse> {
        const response = await this.updateVmRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
