/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.18
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import * as runtime from '../runtime.js';
import { CreateVpnConnectionRequestToJSON, CreateVpnConnectionResponseFromJSON, CreateVpnConnectionRouteRequestToJSON, CreateVpnConnectionRouteResponseFromJSON, DeleteVpnConnectionRequestToJSON, DeleteVpnConnectionResponseFromJSON, DeleteVpnConnectionRouteRequestToJSON, DeleteVpnConnectionRouteResponseFromJSON, ReadVpnConnectionsRequestToJSON, ReadVpnConnectionsResponseFromJSON, UpdateVpnConnectionRequestToJSON, UpdateVpnConnectionResponseFromJSON, } from '../models/index.js';
/**
 *
 */
export class VpnConnectionApi extends runtime.BaseAPI {
    /**
     */
    createVpnConnectionRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/CreateVpnConnection`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: CreateVpnConnectionRequestToJSON(requestParameters.createVpnConnectionRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => CreateVpnConnectionResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    createVpnConnection(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.createVpnConnectionRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    createVpnConnectionRouteRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/CreateVpnConnectionRoute`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: CreateVpnConnectionRouteRequestToJSON(requestParameters.createVpnConnectionRouteRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => CreateVpnConnectionRouteResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    createVpnConnectionRoute(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.createVpnConnectionRouteRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    deleteVpnConnectionRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/DeleteVpnConnection`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: DeleteVpnConnectionRequestToJSON(requestParameters.deleteVpnConnectionRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => DeleteVpnConnectionResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    deleteVpnConnection(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.deleteVpnConnectionRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    deleteVpnConnectionRouteRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/DeleteVpnConnectionRoute`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: DeleteVpnConnectionRouteRequestToJSON(requestParameters.deleteVpnConnectionRouteRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => DeleteVpnConnectionRouteResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    deleteVpnConnectionRoute(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.deleteVpnConnectionRouteRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    readVpnConnectionsRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/ReadVpnConnections`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: ReadVpnConnectionsRequestToJSON(requestParameters.readVpnConnectionsRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => ReadVpnConnectionsResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    readVpnConnections(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.readVpnConnectionsRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     */
    updateVpnConnectionRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/UpdateVpnConnection`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: UpdateVpnConnectionRequestToJSON(requestParameters.updateVpnConnectionRequest),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => UpdateVpnConnectionResponseFromJSON(jsonValue));
        });
    }
    /**
     */
    updateVpnConnection(requestParameters = {}, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.updateVpnConnectionRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
}
